version: 2.1
jobs:
  build-storybook:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Build Storybook
          command: npm deploy-storybook

workflows:
  deploy:
    jobs:
      - build-storybook
