# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/node:latest
#     working_directory: ~/repo
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             - v1-dependencies-
#       - run:
#           name: Installing Dependencies
#           command: yarn install
#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}
#       - run:
#           name: Test App
#           command: yarn test
#       - run:
#           name: Build Storybook
#           command: yarn deploy-storybook --ci
#       - run:
#           name: Build Release
#           command: |
#             if [ $CIRCLE_BRANCH = "master" ]
#             then
#               yarn release
#             fi

# workflows:
#   deploy:
#     jobs:
#       - build
